apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: git-devops-pipeline-ingress
  namespace: default
spec:
  rules:
    - host: devopstest.lancelewandowski.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: git-devops-pipeline-service
                port:
                  number: 80
  ingressClassName: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: git-devops-pipeline-ingress
  namespace: default
spec:
  rules:
    - host: devopstest.lancelewandowski.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: git-devops-pipeline-service
                port:
                  number: 80
  ingressClassName: nginx
