apiVersion: v1
kind: Service
metadata:
  name: devops-pipeline-service
  namespace: default
spec:
  selector:
    app: devops-pipeline
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
