apiVersion: v1
kind: Service
metadata:
  name: git-devops-pipeline-service
  namespace: default
spec:
  selector:
    app: git-devops-pipeline-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
